@startuml

start
:Intro screen;


repeat
    switch (is left or right button pressed)
        case (right button is pressed)
        :snake game;
            while (While no navigation button is pressed)
                :playing game;
                while (is off switch active) is (active) 
                endwhile (deactive)
            endwhile
        case (left button is pressed) 
        :information;
            while (While no navigation button is pressed)
                :show information;
                while (is off switch active) is (active) 
                endwhile (deactive)
            endwhile
        case (no button is pressed)
    endswitch
while (is off switch active) is (active) 
endwhile (deactive)


@enduml