int tonePin = 8;
int dur = 77;
int longDur = 153;
int delayTime = 85;
int longDelayTime = 170;

//Original from https://github.com/bmai1/yuno/tree/main/projects/badapple 

void midi() {
    tone(tonePin, 311, dur);
    delay(delayTime);
    tone(tonePin, 311, dur);
    delay(delayTime);
    tone(tonePin, 349, dur);
    delay(delayTime);
    tone(tonePin, 415, dur);
    delay(delayTime);
    tone(tonePin, 415, dur);
    delay(delayTime);
    tone(tonePin, 466, dur);
    delay(delayTime);
    delay(longDelayTime);
    tone(tonePin, 466, dur);
    delay(delayTime);
    tone(tonePin, 622, dur);
    delay(delayTime);
    tone(tonePin, 622, dur);
    delay(delayTime);
    tone(tonePin, 554, dur);
    delay(delayTime);
    tone(tonePin, 554, dur);
    delay(delayTime);
    tone(tonePin, 466, dur);
    delay(delayTime);
    delay(longDelayTime);
    tone(tonePin, 466, dur);
    delay(delayTime);
    tone(tonePin, 311, dur);
    delay(delayTime);
    delay(longDelayTime);
    tone(tonePin, 311, dur);
    delay(delayTime);
    tone(tonePin, 466, dur);
    delay(delayTime);
    tone(tonePin, 466, dur);
    delay(delayTime);
    tone(tonePin, 415, dur);
    delay(delayTime);
    tone(tonePin, 415, dur);
    delay(delayTime);
    tone(tonePin, 369, dur);
    delay(delayTime);
    tone(tonePin, 369, dur);
    delay(delayTime);
    tone(tonePin, 349, dur);
    delay(delayTime);
    tone(tonePin, 349, dur);
    delay(delayTime);
    tone(tonePin, 311, dur);
    delay(delayTime);
    tone(tonePin, 311, dur);
    delay(delayTime);
    tone(tonePin, 349, dur);
    delay(delayTime);
    tone(tonePin, 349, dur);
    delay(delayTime);
    tone(tonePin, 369, dur);
    delay(delayTime);
    tone(tonePin, 369, dur);
    delay(delayTime);
    tone(tonePin, 415, dur);
    delay(delayTime);
    tone(tonePin, 415, dur);
    delay(delayTime);
    tone(tonePin, 466, dur);
    delay(delayTime);
    delay(longDelayTime);
    tone(tonePin, 466, dur);
    delay(delayTime);
    tone(tonePin, 415, dur);
    delay(delayTime);
    tone(tonePin, 415, dur);
    delay(delayTime);
    tone(tonePin, 369, dur);
    delay(delayTime);
    tone(tonePin, 369, dur);
    delay(delayTime);
    tone(tonePin, 349, dur);
    delay(delayTime);
    tone(tonePin, 349, dur);
    delay(delayTime);
    tone(tonePin, 311, dur);
    delay(delayTime);
    tone(tonePin, 311, dur);
    delay(delayTime);
    tone(tonePin, 349, dur);
    delay(delayTime);
    tone(tonePin, 349, dur);
    delay(delayTime);
    tone(tonePin, 369, dur);
    delay(delayTime);
    tone(tonePin, 369, dur);
    delay(delayTime);
    tone(tonePin, 349, dur);
    delay(delayTime);
    tone(tonePin, 349, dur);
    delay(delayTime);
    tone(tonePin, 311, dur);
    delay(delayTime);
    tone(tonePin, 311, dur);
    delay(delayTime);
    tone(tonePin, 293, dur);
    delay(delayTime);
    tone(tonePin, 293, dur);
    delay(delayTime);
    tone(tonePin, 349, dur);
    delay(delayTime);
    tone(tonePin, 349, dur);
    delay(delayTime);
    tone(tonePin, 311, dur);
    delay(delayTime);
    tone(tonePin, 311, dur);
    delay(delayTime);
    tone(tonePin, 349, dur);
    delay(delayTime);
    tone(tonePin, 349, dur);
    delay(delayTime);
    tone(tonePin, 369, dur);
    delay(delayTime);
    tone(tonePin, 369, dur);
    delay(delayTime);
    tone(tonePin, 415, dur);
    delay(delayTime);
    tone(tonePin, 415, dur);
    delay(delayTime);
    tone(tonePin, 466, dur);
    delay(delayTime);
    delay(longDelayTime);
    tone(tonePin, 466, dur);
    delay(delayTime);
    tone(tonePin, 622, dur);
    delay(delayTime);
    tone(tonePin, 622, dur);
    delay(delayTime);
    tone(tonePin, 554, dur);
    delay(delayTime);
    tone(tonePin, 554, dur);
    delay(delayTime);
    tone(tonePin, 466, dur);
    delay(delayTime);
    delay(longDelayTime);
    tone(tonePin, 466, dur);
    delay(delayTime);
    tone(tonePin, 311, dur);
    delay(delayTime);
    delay(longDelayTime);
    tone(tonePin, 311, dur);
    delay(delayTime);
    tone(tonePin, 466, dur);
    delay(delayTime);
    tone(tonePin, 466, dur);
    delay(delayTime);
    tone(tonePin, 415, dur);
    delay(delayTime);
    tone(tonePin, 415, dur);
    delay(delayTime);
    tone(tonePin, 369, dur);
    delay(delayTime);
    tone(tonePin, 369, dur);
    delay(delayTime);
    tone(tonePin, 349, dur);
    delay(delayTime);
    tone(tonePin, 349, dur);
    delay(delayTime);
    tone(tonePin, 311, dur);
    delay(delayTime);
    tone(tonePin, 311, dur);
    delay(delayTime);
    tone(tonePin, 349, dur);
    delay(delayTime);
    tone(tonePin, 349, dur);
    delay(delayTime);
    tone(tonePin, 369, dur);
    delay(delayTime);
    tone(tonePin, 369, dur);
    delay(delayTime);
    tone(tonePin, 415, dur);
    delay(delayTime);
    tone(tonePin, 415, dur);
    delay(delayTime);
    tone(tonePin, 466, dur);
    delay(delayTime);
    delay(longDelayTime);
    tone(tonePin, 466, dur);
    delay(delayTime);
    tone(tonePin, 415, dur);
    delay(delayTime);
    tone(tonePin, 415, dur);
    delay(delayTime);
    tone(tonePin, 369, dur);
    delay(delayTime);
    tone(tonePin, 369, dur);
    delay(delayTime);
    tone(tonePin, 349, dur);
    delay(delayTime);
    delay(longDelayTime);
    tone(tonePin, 349, dur);
    delay(delayTime);
    tone(tonePin, 369, dur);
    delay(delayTime);
    delay(longDelayTime);
    tone(tonePin, 369, dur);
    delay(delayTime);
    tone(tonePin, 415, dur);
    delay(delayTime);
    delay(longDelayTime);
    tone(tonePin, 415, dur);
    delay(delayTime);
    tone(tonePin, 466, dur);
    delay(delayTime);
    delay(longDelayTime);
    tone(tonePin, 466, dur);
    delay(delayTime);
    tone(tonePin, 311, dur);
    delay(delayTime);
    tone(tonePin, 311, dur);
    delay(delayTime);
    tone(tonePin, 349, dur);
    delay(delayTime);
    tone(tonePin, 349, dur);
    delay(delayTime);
    tone(tonePin, 369, dur);
    delay(delayTime);
    tone(tonePin, 369, dur);
    delay(delayTime);
    tone(tonePin, 415, dur);
    delay(delayTime);
    tone(tonePin, 415, dur);
    delay(delayTime);
    tone(tonePin, 466, dur);
    delay(delayTime);
    delay(longDelayTime);
    tone(tonePin, 466, dur);
    delay(delayTime);
    tone(tonePin, 622, dur);
    delay(delayTime);
    tone(tonePin, 622, dur);
    delay(delayTime);
    tone(tonePin, 554, dur);
    delay(delayTime);
    tone(tonePin, 554, dur);
    delay(delayTime);
    tone(tonePin, 466, dur);
    delay(delayTime);
    delay(longDelayTime);
    tone(tonePin, 466, dur);
    delay(delayTime);
    tone(tonePin, 311, dur);
    delay(delayTime);
    delay(longDelayTime);
    tone(tonePin, 311, dur);
    delay(delayTime);
    tone(tonePin, 466, dur);
    delay(delayTime);
    tone(tonePin, 466, dur);
    delay(delayTime);
    tone(tonePin, 415, dur);
    delay(delayTime);
    tone(tonePin, 415, dur);
    delay(delayTime);
    tone(tonePin, 369, dur);
    delay(delayTime);
    tone(tonePin, 369, dur);
    delay(delayTime);
    tone(tonePin, 349, dur);
    delay(delayTime);
    tone(tonePin, 349, dur);
    delay(delayTime);
    tone(tonePin, 311, dur);
    delay(delayTime);
    tone(tonePin, 311, dur);
    delay(delayTime);
    tone(tonePin, 349, dur);
    delay(delayTime);
    tone(tonePin, 349, dur);
    delay(delayTime);
    tone(tonePin, 369, dur);
    delay(delayTime);
    tone(tonePin, 369, dur);
    delay(delayTime);
    tone(tonePin, 415, dur);
    delay(delayTime);
    tone(tonePin, 415, dur);
    delay(delayTime);
    tone(tonePin, 466, dur);
    delay(delayTime);
    delay(longDelayTime);
    tone(tonePin, 466, dur);
    delay(delayTime);
    tone(tonePin, 415, dur);
    delay(delayTime);
    tone(tonePin, 415, dur);
    delay(delayTime);
    tone(tonePin, 369, dur);
    delay(delayTime);
    tone(tonePin, 369, dur);
    delay(delayTime);
    tone(tonePin, 349, dur);
    delay(delayTime);
    tone(tonePin, 349, dur);
    delay(delayTime);
    tone(tonePin, 311, dur);
    delay(delayTime);
    tone(tonePin, 311, dur);
    delay(delayTime);
    tone(tonePin, 349, dur);
    delay(delayTime);
    tone(tonePin, 349, dur);
    delay(delayTime);
    tone(tonePin, 369, dur);
    delay(delayTime);
    tone(tonePin, 369, dur);
    delay(delayTime);
    tone(tonePin, 349, dur);
    delay(delayTime);
    tone(tonePin, 349, dur);
    delay(delayTime);
    tone(tonePin, 311, dur);
    delay(delayTime);
    tone(tonePin, 311, dur);
    delay(delayTime);
    tone(tonePin, 293, dur);
    delay(delayTime);
    tone(tonePin, 293, dur);
    delay(delayTime);
    tone(tonePin, 349, dur);
    delay(delayTime);
    tone(tonePin, 349, dur);
    delay(delayTime);
    tone(tonePin, 311, dur);
    delay(delayTime);
    tone(tonePin, 311, dur);
    delay(delayTime);
    tone(tonePin, 349, dur);
    delay(delayTime);
    tone(tonePin, 349, dur);
    delay(delayTime);
    tone(tonePin, 369, dur);
    delay(delayTime);
    tone(tonePin, 369, dur);
    delay(delayTime);
    tone(tonePin, 415, dur);
    delay(delayTime);
    tone(tonePin, 415, dur);
    delay(delayTime);
    tone(tonePin, 466, dur);
    delay(delayTime);
    delay(longDelayTime);
    tone(tonePin, 466, dur);
    delay(delayTime);
    tone(tonePin, 622, dur);
    delay(delayTime);
    tone(tonePin, 622, dur);
    delay(delayTime);
    tone(tonePin, 554, dur);
    delay(delayTime);
    tone(tonePin, 554, dur);
    delay(delayTime);
    tone(tonePin, 466, dur);
    delay(delayTime);
    delay(longDelayTime);
    tone(tonePin, 466, dur);
    delay(delayTime);
    tone(tonePin, 311, dur);
    delay(delayTime);
    delay(longDelayTime);
    tone(tonePin, 311, dur);
    delay(delayTime);
    tone(tonePin, 466, dur);
    delay(delayTime);
    tone(tonePin, 466, dur);
    delay(delayTime);
    tone(tonePin, 415, dur);
    delay(delayTime);
    tone(tonePin, 415, dur);
    delay(delayTime);
    tone(tonePin, 369, dur);
    delay(delayTime);
    tone(tonePin, 369, dur);
    delay(delayTime);
    tone(tonePin, 349, dur);
    delay(delayTime);
    tone(tonePin, 349, dur);
    delay(delayTime);
    tone(tonePin, 311, dur);
    delay(delayTime);
    tone(tonePin, 311, dur);
    delay(delayTime);
    tone(tonePin, 349, dur);
    delay(delayTime);
    tone(tonePin, 349, dur);
    delay(delayTime);
    tone(tonePin, 369, dur);
    delay(delayTime);
    tone(tonePin, 369, dur);
    delay(delayTime);
    tone(tonePin, 415, dur);
    delay(delayTime);
    tone(tonePin, 415, dur);
    delay(delayTime);
    tone(tonePin, 466, dur);
    delay(delayTime);
    delay(longDelayTime);
    tone(tonePin, 466, dur);
    delay(delayTime);
    tone(tonePin, 415, dur);
    delay(delayTime);
    tone(tonePin, 415, dur);
    delay(delayTime);
    tone(tonePin, 369, dur);
    delay(delayTime);
    tone(tonePin, 369, dur);
    delay(delayTime);
    tone(tonePin, 349, dur);
    delay(delayTime);
    delay(longDelayTime);
    tone(tonePin, 349, dur);
    delay(delayTime);
    tone(tonePin, 369, dur);
    delay(delayTime);
    delay(longDelayTime);
    tone(tonePin, 369, dur);
    delay(delayTime);
    tone(tonePin, 415, dur);
    delay(delayTime);
    delay(longDelayTime);
    tone(tonePin, 415, dur);
    delay(delayTime);
    tone(tonePin, 466, dur);
    delay(delayTime);
    delay(longDelayTime);
    tone(tonePin, 466, dur);
    delay(delayTime);
    tone(tonePin, 554, dur);
    delay(delayTime);
    tone(tonePin, 554, dur);
    delay(delayTime);
    tone(tonePin, 622, dur);
    delay(delayTime);
    tone(tonePin, 622, dur);
    delay(delayTime);
    tone(tonePin, 466, dur);
    delay(delayTime);
    tone(tonePin, 466, dur);
    delay(delayTime);
    tone(tonePin, 415, dur);
    delay(delayTime);
    tone(tonePin, 415, dur);
    delay(delayTime);
    tone(tonePin, 466, dur);
    delay(delayTime);
    delay(longDelayTime);
    tone(tonePin, 466, dur);
    delay(delayTime);
    tone(tonePin, 415, dur);
    delay(delayTime);
    tone(tonePin, 415, dur);
    delay(delayTime);
    tone(tonePin, 466, dur);
    delay(delayTime);
    tone(tonePin, 466, dur);
    delay(delayTime);
    tone(tonePin, 554, dur);
    delay(delayTime);
    tone(tonePin, 554, dur);
    delay(delayTime);
    tone(tonePin, 622, dur);
    delay(delayTime);
    tone(tonePin, 622, dur);
    delay(delayTime);
    tone(tonePin, 466, dur);
    delay(delayTime);
    tone(tonePin, 466, dur);
    delay(delayTime);
    tone(tonePin, 415, dur);
    delay(delayTime);
    tone(tonePin, 415, dur);
    delay(delayTime);
    tone(tonePin, 466, dur);
    delay(delayTime);
    delay(longDelayTime);
    tone(tonePin, 466, dur);
    delay(delayTime);
    tone(tonePin, 415, dur);
    delay(delayTime);
    tone(tonePin, 415, dur);
    delay(delayTime);
    tone(tonePin, 466, dur);
    delay(delayTime);
    tone(tonePin, 466, dur);
    delay(delayTime);
    tone(tonePin, 415, dur);
    delay(delayTime);
    tone(tonePin, 415, dur);
    delay(delayTime);
    tone(tonePin, 369, dur);
    delay(delayTime);
    tone(tonePin, 369, dur);
    delay(delayTime);
    tone(tonePin, 349, dur);
    delay(delayTime);
    tone(tonePin, 349, dur);
    delay(delayTime);
    tone(tonePin, 277, dur);
    delay(delayTime);
    tone(tonePin, 277, dur);
    delay(delayTime);
    tone(tonePin, 311, dur);
    delay(delayTime);
    delay(longDelayTime);
    tone(tonePin, 311, dur);
    delay(delayTime);
    tone(tonePin, 277, dur);
    delay(delayTime);
    tone(tonePin, 277, dur);
    delay(delayTime);
    tone(tonePin, 311, dur);
    delay(delayTime);
    tone(tonePin, 311, dur);
    delay(delayTime);
    tone(tonePin, 349, dur);
    delay(delayTime);
    tone(tonePin, 349, dur);
    delay(delayTime);
    tone(tonePin, 369, dur);
    delay(delayTime);
    tone(tonePin, 369, dur);
    delay(delayTime);
    tone(tonePin, 415, dur);
    delay(delayTime);
    tone(tonePin, 415, dur);
    delay(delayTime);
    tone(tonePin, 466, dur);
    delay(delayTime);
    tone(tonePin, 466, dur);
    delay(delayTime);
    tone(tonePin, 311, dur);
    delay(delayTime);
    delay(longDelayTime);
    tone(tonePin, 311, dur);
    delay(delayTime);
    tone(tonePin, 466, dur);
    delay(delayTime);
    tone(tonePin, 466, dur);
    delay(delayTime);
    tone(tonePin, 554, dur);
    delay(delayTime);
    tone(tonePin, 554, dur);
    delay(delayTime);
    tone(tonePin, 554, dur);
    delay(delayTime);
    tone(tonePin, 554, dur);
    delay(delayTime);
    tone(tonePin, 622, dur);
    delay(delayTime);
    tone(tonePin, 622, dur);
    delay(delayTime);
    tone(tonePin, 466, dur);
    delay(delayTime);
    tone(tonePin, 466, dur);
    delay(delayTime);
    tone(tonePin, 415, dur);
    delay(delayTime);
    tone(tonePin, 415, dur);
    delay(delayTime);
    tone(tonePin, 466, dur);
    delay(delayTime);
    delay(longDelayTime);
    tone(tonePin, 466, dur);
    delay(delayTime);
    tone(tonePin, 415, dur);
    delay(delayTime);
    tone(tonePin, 415, dur);
    delay(delayTime);
    tone(tonePin, 466, dur);
    delay(delayTime);
    tone(tonePin, 466, dur);
    delay(delayTime);
    tone(tonePin, 554, dur);
    delay(delayTime);
    tone(tonePin, 554, dur);
    delay(delayTime);
    tone(tonePin, 622, dur);
    delay(delayTime);
    tone(tonePin, 622, dur);
    delay(delayTime);
    tone(tonePin, 466, dur);
    delay(delayTime);
    tone(tonePin, 466, dur);
    delay(delayTime);
    tone(tonePin, 415, dur);
    delay(delayTime);
    tone(tonePin, 415, dur);
    delay(delayTime);
    tone(tonePin, 466, dur);
    delay(delayTime);
    delay(longDelayTime);
    tone(tonePin, 466, dur);
    delay(delayTime);
    tone(tonePin, 415, dur);
    delay(delayTime);
    tone(tonePin, 415, dur);
    delay(delayTime);
    tone(tonePin, 466, dur);
    delay(delayTime);
    tone(tonePin, 466, dur);
    delay(delayTime);
    tone(tonePin, 415, dur);
    delay(delayTime);
    tone(tonePin, 415, dur);
    delay(delayTime);
    tone(tonePin, 369, dur);
    delay(delayTime);
    tone(tonePin, 369, dur);
    delay(delayTime);
    tone(tonePin, 349, dur);
    delay(delayTime);
    tone(tonePin, 349, dur);
    delay(delayTime);
    tone(tonePin, 277, dur);
    delay(delayTime);
    tone(tonePin, 277, dur);
    delay(delayTime);
    tone(tonePin, 311, dur);
    delay(delayTime);
    delay(longDelayTime);
    tone(tonePin, 311, dur);
    delay(delayTime);
    tone(tonePin, 277, dur);
    delay(delayTime);
    tone(tonePin, 277, dur);
    delay(delayTime);
    tone(tonePin, 311, dur);
    delay(delayTime);
    tone(tonePin, 311, dur);
    delay(delayTime);
    tone(tonePin, 349, dur);
    delay(delayTime);
    tone(tonePin, 349, dur);
    delay(delayTime);
    tone(tonePin, 369, dur);
    delay(delayTime);
    tone(tonePin, 369, dur);
    delay(delayTime);
    tone(tonePin, 415, dur);
    delay(delayTime);
    tone(tonePin, 415, dur);
    delay(delayTime);
    tone(tonePin, 466, dur);
    delay(delayTime);
    tone(tonePin, 466, dur);
    delay(delayTime);
    tone(tonePin, 311, dur);
    delay(delayTime);
    delay(longDelayTime);
    tone(tonePin, 311, dur);
    delay(delayTime);
    tone(tonePin, 466, dur);
    delay(delayTime);
    tone(tonePin, 466, dur);
    delay(delayTime);
    tone(tonePin, 554, dur);
    delay(delayTime);
    tone(tonePin, 554, dur);
    delay(delayTime);
    tone(tonePin, 554, dur);
    delay(delayTime);
    tone(tonePin, 554, dur);
    delay(delayTime);
    tone(tonePin, 622, dur);
    delay(delayTime);
    tone(tonePin, 622, dur);
    delay(delayTime);
    tone(tonePin, 466, dur);
    delay(delayTime);
    tone(tonePin, 466, dur);
    delay(delayTime);
    tone(tonePin, 415, dur);
    delay(delayTime);
    tone(tonePin, 415, dur);
    delay(delayTime);
    tone(tonePin, 466, dur);
    delay(delayTime);
    delay(longDelayTime);
    tone(tonePin, 466, dur);
    delay(delayTime);
    tone(tonePin, 415, dur);
    delay(delayTime);
    tone(tonePin, 415, dur);
    delay(delayTime);
    tone(tonePin, 466, dur);
    delay(delayTime);
    tone(tonePin, 466, dur);
    delay(delayTime);
    tone(tonePin, 554, dur);
    delay(delayTime);
    tone(tonePin, 554, dur);
    delay(delayTime);
    tone(tonePin, 622, dur);
    delay(delayTime);
    tone(tonePin, 622, dur);
    delay(delayTime);
    tone(tonePin, 466, dur);
    delay(delayTime);
    tone(tonePin, 466, dur);
    delay(delayTime);
    tone(tonePin, 415, dur);
    delay(delayTime);
    tone(tonePin, 415, dur);
    delay(delayTime);
    tone(tonePin, 466, dur);
    delay(delayTime);
    delay(longDelayTime);
    tone(tonePin, 466, dur);
    delay(delayTime);
    tone(tonePin, 415, dur);
    delay(delayTime);
    tone(tonePin, 415, dur);
    delay(delayTime);
    tone(tonePin, 466, dur);
    delay(delayTime);
    tone(tonePin, 466, dur);
    delay(delayTime);
    tone(tonePin, 415, dur);
    delay(delayTime);
    tone(tonePin, 415, dur);
    delay(delayTime);
    tone(tonePin, 369, dur);
    delay(delayTime);
    tone(tonePin, 369, dur);
    delay(delayTime);
    tone(tonePin, 349, dur);
    delay(delayTime);
    tone(tonePin, 349, dur);
    delay(delayTime);
    tone(tonePin, 277, dur);
    delay(delayTime);
    tone(tonePin, 277, dur);
    delay(delayTime);
    tone(tonePin, 311, dur);
    delay(delayTime);
    delay(longDelayTime);
    tone(tonePin, 311, dur);
    delay(delayTime);
    tone(tonePin, 277, dur);
    delay(delayTime);
    tone(tonePin, 277, dur);
    delay(delayTime);
    tone(tonePin, 311, dur);
    delay(delayTime);
    tone(tonePin, 311, dur);
    delay(delayTime);
    tone(tonePin, 349, dur);
    delay(delayTime);
    tone(tonePin, 349, dur);
    delay(delayTime);
    tone(tonePin, 369, dur);
    delay(delayTime);
    tone(tonePin, 369, dur);
    delay(delayTime);
    tone(tonePin, 415, dur);
    delay(delayTime);
    tone(tonePin, 415, dur);
    delay(delayTime);
    tone(tonePin, 466, dur);
    delay(delayTime);
    tone(tonePin, 466, dur);
    delay(delayTime);
    tone(tonePin, 311, dur);
    delay(delayTime);
    delay(longDelayTime);
    tone(tonePin, 311, dur);
    delay(delayTime);
    tone(tonePin, 466, dur);
    delay(delayTime);
    tone(tonePin, 466, dur);
    delay(delayTime);
    tone(tonePin, 554, dur);
    delay(delayTime);
    tone(tonePin, 554, dur);
    delay(delayTime);
    tone(tonePin, 554, dur);
    delay(delayTime);
    tone(tonePin, 554, dur);
    delay(delayTime);
    tone(tonePin, 622, dur);
    delay(delayTime);
    tone(tonePin, 622, dur);
    delay(delayTime);
    tone(tonePin, 466, dur);
    delay(delayTime);
    tone(tonePin, 466, dur);
    delay(delayTime);
    tone(tonePin, 415, dur);
    delay(delayTime);
    tone(tonePin, 415, dur);
    delay(delayTime);
    tone(tonePin, 466, dur);
    delay(delayTime);
    delay(longDelayTime);
    tone(tonePin, 466, dur);
    delay(delayTime);
    tone(tonePin, 415, dur);
    delay(delayTime);
    tone(tonePin, 415, dur);
    delay(delayTime);
    tone(tonePin, 466, dur);
    delay(delayTime);
    tone(tonePin, 466, dur);
    delay(delayTime);
    tone(tonePin, 554, dur);
    delay(delayTime);
    tone(tonePin, 554, dur);
    delay(delayTime);
    tone(tonePin, 622, dur);
    delay(delayTime);
    tone(tonePin, 622, dur);
    delay(delayTime);
    tone(tonePin, 466, dur);
    delay(delayTime);
    tone(tonePin, 466, dur);
    delay(delayTime);
    tone(tonePin, 415, dur);
    delay(delayTime);
    tone(tonePin, 415, dur);
    delay(delayTime);
    tone(tonePin, 466, dur);
    delay(delayTime);
    delay(longDelayTime);
    tone(tonePin, 466, dur);
    delay(delayTime);
    tone(tonePin, 622, dur);
    delay(delayTime);
    tone(tonePin, 622, dur);
    delay(delayTime);
    tone(tonePin, 698, dur);
    delay(delayTime);
    tone(tonePin, 698, dur);
    delay(delayTime);
    tone(tonePin, 739, dur);
    delay(delayTime);
    tone(tonePin, 739, dur);
    delay(delayTime);
    tone(tonePin, 698, dur);
    delay(delayTime);
    tone(tonePin, 698, dur);
    delay(delayTime);
    tone(tonePin, 622, dur);
    delay(delayTime);
    tone(tonePin, 622, dur);
    delay(delayTime);
    tone(tonePin, 554, dur);
    delay(delayTime);
    tone(tonePin, 554, dur);
    delay(delayTime);
    tone(tonePin, 466, dur);
    delay(delayTime);
    delay(longDelayTime);
    tone(tonePin, 466, dur);
    delay(delayTime);
    tone(tonePin, 415, dur);
    delay(delayTime);
    tone(tonePin, 415, dur);
    delay(delayTime);
    tone(tonePin, 466, dur);
    delay(delayTime);
    tone(tonePin, 466, dur);
    delay(delayTime);
    tone(tonePin, 415, dur);
    delay(delayTime);
    tone(tonePin, 415, dur);
    delay(delayTime);
    tone(tonePin, 369, dur);
    delay(delayTime);
    tone(tonePin, 369, dur);
    delay(delayTime);
    tone(tonePin, 349, dur);
    delay(delayTime);
    tone(tonePin, 349, dur);
    delay(delayTime);
    tone(tonePin, 277, dur);
    delay(delayTime);
    tone(tonePin, 277, dur);
    delay(delayTime);
    tone(tonePin, 311, dur);
    delay(delayTime);
    delay(longDelayTime);
    tone(tonePin, 311, dur);
    delay(delayTime);
    tone(tonePin, 466, dur);
    delay(delayTime);
    tone(tonePin, 466, dur);
    delay(delayTime);
    tone(tonePin, 554, dur);
    delay(delayTime);
    tone(tonePin, 554, dur);
    delay(delayTime);
    tone(tonePin, 554, longDur);
    delay(longDelayTime);
    tone(tonePin, 622, longDur);
    delay(longDelayTime);
    tone(tonePin, 466, longDur);
    delay(longDelayTime);
    tone(tonePin, 415, longDur);
    delay(longDelayTime);
    tone(tonePin, 466, dur);
    delay(delayTime);
    delay(longDelayTime);
    tone(tonePin, 466, dur);
    delay(delayTime);
    tone(tonePin, 415, longDur);
    delay(longDelayTime);
    tone(tonePin, 466, longDur);
    delay(longDelayTime);
    tone(tonePin, 554, longDur);
    delay(longDelayTime);
    tone(tonePin, 622, longDur);
    delay(longDelayTime);
    tone(tonePin, 466, longDur);
    delay(longDelayTime);
    tone(tonePin, 415, longDur);
    delay(longDelayTime);
    tone(tonePin, 466, dur);
    delay(delayTime);
    delay(longDelayTime);
    tone(tonePin, 466, dur);
    delay(delayTime);
    tone(tonePin, 415, longDur);
    delay(longDelayTime);
    tone(tonePin, 466, longDur);
    delay(longDelayTime);
    tone(tonePin, 415, longDur);
    delay(longDelayTime);
    tone(tonePin, 369, longDur);
    delay(longDelayTime);
    tone(tonePin, 349, longDur);
    delay(longDelayTime);
    tone(tonePin, 277, longDur);
    delay(longDelayTime);
    tone(tonePin, 311, dur);
    delay(delayTime);
    delay(longDelayTime);
    tone(tonePin, 311, dur);
    delay(delayTime);
    tone(tonePin, 277, longDur);
    delay(longDelayTime);
    tone(tonePin, 311, longDur);
    delay(longDelayTime);
    tone(tonePin, 349, longDur);
    delay(longDelayTime);
    tone(tonePin, 369, longDur);
    delay(longDelayTime);
    tone(tonePin, 415, longDur);
    delay(longDelayTime);
    tone(tonePin, 466, longDur);
    delay(longDelayTime);
    tone(tonePin, 311, dur);
    delay(delayTime);
    delay(longDelayTime);
    tone(tonePin, 311, dur);
    delay(delayTime);
    tone(tonePin, 466, longDur);
    delay(longDelayTime);
    tone(tonePin, 554, longDur);
    delay(longDelayTime);
    tone(tonePin, 554, longDur);
    delay(longDelayTime);
    tone(tonePin, 622, longDur);
    delay(longDelayTime);
    tone(tonePin, 466, longDur);
    delay(longDelayTime);
    tone(tonePin, 415, longDur);
    delay(longDelayTime);
    tone(tonePin, 466, dur);
    delay(delayTime);
    delay(longDelayTime);
    tone(tonePin, 466, dur);
    delay(delayTime);
    tone(tonePin, 415, longDur);
    delay(longDelayTime);
    tone(tonePin, 466, longDur);
    delay(longDelayTime);
    tone(tonePin, 554, longDur);
    delay(longDelayTime);
    tone(tonePin, 622, longDur);
    delay(longDelayTime);
    tone(tonePin, 466, longDur);
    delay(longDelayTime);
    tone(tonePin, 415, longDur);
    delay(longDelayTime);
    tone(tonePin, 466, dur);
    delay(delayTime);
    delay(longDelayTime);
    tone(tonePin, 466, dur);
    delay(delayTime);
    tone(tonePin, 415, longDur);
    delay(longDelayTime);
    delay(delayTime);
    tone(tonePin, 138, dur);
    delay(delayTime);
    tone(tonePin, 155, dur);
    delay(delayTime);
    tone(tonePin, 415, dur);
    delay(delayTime);
    tone(tonePin, 369, longDur);
    delay(longDelayTime);
    tone(tonePin, 349, longDur);
    delay(longDelayTime);
    tone(tonePin, 277, longDur);
    delay(longDelayTime);
    tone(tonePin, 311, dur);
    delay(delayTime);
    delay(longDelayTime);
    tone(tonePin, 311, dur);
    delay(delayTime);
    tone(tonePin, 277, longDur);
    delay(longDelayTime);
    delay(delayTime);
    tone(tonePin, 155, dur);
    delay(delayTime);
    tone(tonePin, 155, dur);
    delay(delayTime);
    tone(tonePin, 349, dur);
    delay(delayTime);
    tone(tonePin, 369, longDur);
    delay(longDelayTime);
    tone(tonePin, 415, longDur);
    delay(longDelayTime);
    tone(tonePin, 466, longDur);
    delay(longDelayTime);
    tone(tonePin, 311, dur);
    delay(delayTime);
    delay(longDelayTime);
    tone(tonePin, 311, dur);
    delay(delayTime);
    tone(tonePin, 466, longDur);
    delay(longDelayTime);
    delay(delayTime);
    tone(tonePin, 155, dur);
    delay(delayTime);
    tone(tonePin, 123, dur);
    delay(delayTime);
    tone(tonePin, 554, dur);
    delay(delayTime);
    tone(tonePin, 622, longDur);
    delay(longDelayTime);
    tone(tonePin, 466, longDur);
    delay(longDelayTime);
    tone(tonePin, 415, longDur);
    delay(longDelayTime);
    tone(tonePin, 466, dur);
    delay(delayTime);
    delay(longDelayTime);
    tone(tonePin, 466, dur);
    delay(delayTime);
    tone(tonePin, 415, longDur);
    delay(longDelayTime);
    delay(delayTime);
    tone(tonePin, 123, dur);
    delay(delayTime);
    tone(tonePin, 138, dur);
    delay(delayTime);
    tone(tonePin, 554, dur);
    delay(delayTime);
    tone(tonePin, 622, longDur);
    delay(longDelayTime);
    tone(tonePin, 466, longDur);
    delay(longDelayTime);
    tone(tonePin, 415, longDur);
    delay(longDelayTime);
    tone(tonePin, 466, dur);
    delay(delayTime);
    delay(longDelayTime);
    tone(tonePin, 466, dur);
    delay(delayTime);
    tone(tonePin, 415, longDur);
    delay(longDelayTime);
    delay(delayTime);
    tone(tonePin, 138, dur);
    delay(delayTime);
    tone(tonePin, 155, dur);
    delay(delayTime);
    tone(tonePin, 415, dur);
    delay(delayTime);
    tone(tonePin, 369, longDur);
    delay(longDelayTime);
    tone(tonePin, 349, longDur);
    delay(longDelayTime);
    tone(tonePin, 277, longDur);
    delay(longDelayTime);
    tone(tonePin, 311, dur);
    delay(delayTime);
    delay(longDelayTime);
    tone(tonePin, 311, dur);
    delay(delayTime);
    tone(tonePin, 277, longDur);
    delay(longDelayTime);
    delay(delayTime);
    tone(tonePin, 155, dur);
    delay(delayTime);
    tone(tonePin, 155, dur);
    delay(delayTime);
    tone(tonePin, 349, dur);
    delay(delayTime);
    tone(tonePin, 369, longDur);
    delay(longDelayTime);
    tone(tonePin, 415, longDur);
    delay(longDelayTime);
    tone(tonePin, 466, longDur);
    delay(longDelayTime);
    tone(tonePin, 311, dur);
    delay(delayTime);
    delay(longDelayTime);
    tone(tonePin, 311, dur);
    delay(delayTime);
    tone(tonePin, 466, longDur);
    delay(longDelayTime);
    delay(delayTime);
    tone(tonePin, 155, dur);
    delay(delayTime);
    tone(tonePin, 123, dur);
    delay(delayTime);
    tone(tonePin, 554, dur);
    delay(delayTime);
    tone(tonePin, 622, longDur);
    delay(longDelayTime);
    tone(tonePin, 466, longDur);
    delay(longDelayTime);
    tone(tonePin, 415, longDur);
    delay(longDelayTime);
    tone(tonePin, 466, dur);
    delay(delayTime);
    delay(longDelayTime);
    tone(tonePin, 466, dur);
    delay(delayTime);
    tone(tonePin, 415, longDur);
    delay(longDelayTime);
    delay(delayTime);
    tone(tonePin, 123, dur);
    delay(delayTime);
    tone(tonePin, 138, dur);
    delay(delayTime);
    tone(tonePin, 554, dur);
    delay(delayTime);
    tone(tonePin, 622, longDur);
    delay(longDelayTime);
    tone(tonePin, 466, longDur);
    delay(longDelayTime);
    tone(tonePin, 415, longDur);
    delay(longDelayTime);
    tone(tonePin, 466, dur);
    delay(delayTime);
    delay(longDelayTime);
    tone(tonePin, 466, dur);
    delay(delayTime);
    tone(tonePin, 622, longDur);
    delay(longDelayTime);
    delay(delayTime);
    tone(tonePin, 138, dur);
    delay(delayTime);
    tone(tonePin, 155, dur);
    delay(delayTime);
    tone(tonePin, 739, dur);
    delay(delayTime);
    tone(tonePin, 698, longDur);
    delay(longDelayTime);
    tone(tonePin, 622, longDur);
    delay(longDelayTime);
    tone(tonePin, 554, longDur);
    delay(longDelayTime);
    tone(tonePin, 466, dur);
    delay(delayTime);
    delay(longDelayTime);
    tone(tonePin, 466, dur);
    delay(delayTime);
    tone(tonePin, 415, longDur);
    delay(longDelayTime);
    delay(delayTime);
    tone(tonePin, 155, dur);
    delay(delayTime);
    tone(tonePin, 415, longDur);
    delay(longDelayTime);
    tone(tonePin, 369, longDur);
    delay(longDelayTime);
    tone(tonePin, 349, longDur);
    delay(longDelayTime);
    tone(tonePin, 277, longDur);
    delay(longDelayTime);
    tone(tonePin, 207, dur);
    delay(delayTime);
    delay(longDelayTime);
    tone(tonePin, 207, dur);
    delay(delayTime);
    tone(tonePin, 184, dur);
    delay(delayTime);
    delay(longDelayTime);
    tone(tonePin, 184, dur);
    delay(delayTime);
    tone(tonePin, 311, dur);
    delay(delayTime);
    delay(delayTime);
    tone(tonePin, 311, dur);
    delay(delayTime);
    tone(tonePin, 311, dur);
    delay(delayTime);
    delay(delayTime);
    tone(tonePin, 311, dur);
    delay(delayTime);
    tone(tonePin, 233, dur);
    delay(delayTime);
    tone(tonePin, 277, dur);
    delay(delayTime);
    tone(tonePin, 311, dur);
    delay(delayTime);
    delay(delayTime);
    tone(tonePin, 311, dur);
    delay(delayTime);
    tone(tonePin, 311, dur);
    delay(delayTime);
    delay(delayTime);
    tone(tonePin, 311, dur);
    delay(delayTime);
    tone(tonePin, 233, dur);
    delay(delayTime);
    tone(tonePin, 277, dur);
    delay(delayTime);
    tone(tonePin, 311, dur);
    delay(delayTime);
    delay(delayTime);
    tone(tonePin, 311, dur);
    delay(delayTime);
    tone(tonePin, 311, dur);
    delay(delayTime);
    delay(delayTime);
    tone(tonePin, 311, dur);
    delay(delayTime);
    tone(tonePin, 233, dur);
    delay(delayTime);
    tone(tonePin, 277, dur);
    delay(delayTime);
    tone(tonePin, 311, dur);
    delay(delayTime);
    tone(tonePin, 311, dur);
    delay(delayTime);
    tone(tonePin, 277, dur);
    delay(delayTime);
    tone(tonePin, 311, dur);
    delay(delayTime);
    tone(tonePin, 207, dur);
    delay(delayTime);
    tone(tonePin, 207, dur);
    delay(delayTime);
    tone(tonePin, 184, dur);
    delay(delayTime);
    tone(tonePin, 207, dur);
    delay(delayTime);
    tone(tonePin, 311, dur);
    delay(delayTime);
    delay(delayTime);
    tone(tonePin, 311, dur);
    delay(delayTime);
    tone(tonePin, 311, dur);
    delay(delayTime);
    delay(delayTime);
    tone(tonePin, 311, dur);
    delay(delayTime);
    tone(tonePin, 233, dur);
    delay(delayTime);
    tone(tonePin, 277, dur);
    delay(delayTime);
    tone(tonePin, 311, dur);
    delay(delayTime);
    delay(delayTime);
    tone(tonePin, 311, dur);
    delay(delayTime);
    tone(tonePin, 311, dur);
    delay(delayTime);
    delay(delayTime);
    tone(tonePin, 311, dur);
    delay(delayTime);
    tone(tonePin, 233, dur);
    delay(delayTime);
    tone(tonePin, 277, dur);
    delay(delayTime);
    tone(tonePin, 311, dur);
    delay(delayTime);
    delay(delayTime);
    tone(tonePin, 311, dur);
    delay(delayTime);
    tone(tonePin, 311, dur);
    delay(delayTime);
    delay(delayTime);
    tone(tonePin, 311, dur);
    delay(delayTime);
    tone(tonePin, 233, dur);
    delay(delayTime);
    tone(tonePin, 277, dur);
    delay(delayTime);
    tone(tonePin, 207, dur);
    delay(delayTime);
    tone(tonePin, 207, dur);
    delay(delayTime);
    tone(tonePin, 369, dur);
    delay(delayTime);
    tone(tonePin, 207, dur);
    delay(delayTime);
    tone(tonePin, 369, dur);
    delay(delayTime);
    tone(tonePin, 369, dur);
    delay(delayTime);
    tone(tonePin, 349, dur);
    delay(delayTime);
    tone(tonePin, 369, dur);
    delay(delayTime);
    tone(tonePin, 311, dur);
    delay(delayTime);
    delay(delayTime);
    tone(tonePin, 311, dur);
    delay(delayTime);
    tone(tonePin, 311, dur);
    delay(delayTime);
    delay(delayTime);
    tone(tonePin, 311, dur);
    delay(delayTime);
    tone(tonePin, 233, dur);
    delay(delayTime);
    tone(tonePin, 277, dur);
    delay(delayTime);
    tone(tonePin, 311, dur);
    delay(delayTime);
    delay(delayTime);
    tone(tonePin, 311, dur);
    delay(delayTime);
    tone(tonePin, 311, dur);
    delay(delayTime);
    delay(delayTime);
    tone(tonePin, 311, dur);
    delay(delayTime);
    tone(tonePin, 233, dur);
    delay(delayTime);
    tone(tonePin, 277, dur);
    delay(delayTime);
    tone(tonePin, 311, dur);
    delay(delayTime);
    delay(delayTime);
    tone(tonePin, 311, dur);
    delay(delayTime);
    tone(tonePin, 311, dur);
    delay(delayTime);
    delay(delayTime);
    tone(tonePin, 311, dur);
    delay(delayTime);
    tone(tonePin, 233, dur);
    delay(delayTime);
    tone(tonePin, 277, dur);
    delay(delayTime);
    tone(tonePin, 311, dur);
    delay(delayTime);
    tone(tonePin, 311, dur);
    delay(delayTime);
    tone(tonePin, 277, dur);
    delay(delayTime);
    tone(tonePin, 311, dur);
    delay(delayTime);
    tone(tonePin, 207, dur);
    delay(delayTime);
    tone(tonePin, 207, dur);
    delay(delayTime);
    tone(tonePin, 369, dur);
    delay(delayTime);
    tone(tonePin, 207, dur);
    delay(delayTime);
    tone(tonePin, 311, dur);
    delay(delayTime);
    delay(delayTime);
    tone(tonePin, 311, dur);
    delay(delayTime);
    tone(tonePin, 311, dur);
    delay(delayTime);
    delay(delayTime);
    tone(tonePin, 311, dur);
    delay(delayTime);
    tone(tonePin, 233, dur);
    delay(delayTime);
    tone(tonePin, 277, dur);
    delay(delayTime);
    tone(tonePin, 311, dur);
    delay(delayTime);
    delay(delayTime);
    tone(tonePin, 311, dur);
    delay(delayTime);
    tone(tonePin, 311, dur);
    delay(delayTime);
    delay(delayTime);
    tone(tonePin, 311, dur);
    delay(delayTime);
    tone(tonePin, 233, dur);
    delay(delayTime);
    tone(tonePin, 277, dur);
    delay(delayTime);
    tone(tonePin, 311, dur);
    delay(delayTime);
    delay(delayTime);
    tone(tonePin, 311, dur);
    delay(delayTime);
    tone(tonePin, 311, dur);
    delay(delayTime);
    delay(delayTime);
    tone(tonePin, 311, dur);
    delay(delayTime);
    tone(tonePin, 233, dur);
    delay(delayTime);
    tone(tonePin, 277, dur);
    delay(delayTime);
    tone(tonePin, 207, dur);
    delay(delayTime);
    tone(tonePin, 207, dur);
    delay(delayTime);
    tone(tonePin, 369, dur);
    delay(delayTime);
    tone(tonePin, 207, dur);
    delay(delayTime);
    tone(tonePin, 369, dur);
    delay(delayTime);
    tone(tonePin, 369, dur);
    delay(delayTime);
    tone(tonePin, 349, dur);
    delay(delayTime);
    tone(tonePin, 369, dur);
    delay(delayTime);
    tone(tonePin, 311, dur);
    delay(delayTime);
    tone(tonePin, 311, dur);
    delay(delayTime);
    tone(tonePin, 349, dur);
    delay(delayTime);
    tone(tonePin, 349, dur);
    delay(delayTime);
    tone(tonePin, 369, dur);
    delay(delayTime);
    tone(tonePin, 369, dur);
    delay(delayTime);
    tone(tonePin, 415, dur);
    delay(delayTime);
    tone(tonePin, 415, dur);
    delay(delayTime);
    tone(tonePin, 466, dur);
    delay(delayTime);
    delay(longDelayTime);
    tone(tonePin, 466, dur);
    delay(delayTime);
    tone(tonePin, 622, dur);
    delay(delayTime);
    tone(tonePin, 622, dur);
    delay(delayTime);
    tone(tonePin, 554, dur);
    delay(delayTime);
    tone(tonePin, 554, dur);
    delay(delayTime);
    tone(tonePin, 466, dur);
    delay(delayTime);
    delay(longDelayTime);
    tone(tonePin, 466, dur);
    delay(delayTime);
    tone(tonePin, 311, dur);
    delay(delayTime);
    delay(longDelayTime);
    tone(tonePin, 311, dur);
    delay(delayTime);
    tone(tonePin, 466, dur);
    delay(delayTime);
    tone(tonePin, 466, dur);
    delay(delayTime);
    tone(tonePin, 415, dur);
    delay(delayTime);
    tone(tonePin, 415, dur);
    delay(delayTime);
    tone(tonePin, 369, dur);
    delay(delayTime);
    tone(tonePin, 369, dur);
    delay(delayTime);
    tone(tonePin, 349, dur);
    delay(delayTime);
    tone(tonePin, 349, dur);
    delay(delayTime);
    tone(tonePin, 311, dur);
    delay(delayTime);
    tone(tonePin, 311, dur);
    delay(delayTime);
    tone(tonePin, 349, dur);
    delay(delayTime);
    tone(tonePin, 349, dur);
    delay(delayTime);
    tone(tonePin, 369, dur);
    delay(delayTime);
    tone(tonePin, 369, dur);
    delay(delayTime);
    tone(tonePin, 415, dur);
    delay(delayTime);
    tone(tonePin, 415, dur);
    delay(delayTime);
    tone(tonePin, 466, dur);
    delay(delayTime);
    delay(longDelayTime);
    tone(tonePin, 466, dur);
    delay(delayTime);
    tone(tonePin, 415, dur);
    delay(delayTime);
    tone(tonePin, 415, dur);
    delay(delayTime);
    tone(tonePin, 369, dur);
    delay(delayTime);
    tone(tonePin, 369, dur);
    delay(delayTime);
    tone(tonePin, 349, dur);
    delay(delayTime);
    tone(tonePin, 349, dur);
    delay(delayTime);
    tone(tonePin, 311, dur);
    delay(delayTime);
    tone(tonePin, 311, dur);
    delay(delayTime);
    tone(tonePin, 349, dur);
    delay(delayTime);
    tone(tonePin, 349, dur);
    delay(delayTime);
    tone(tonePin, 369, dur);
    delay(delayTime);
    tone(tonePin, 369, dur);
    delay(delayTime);
    tone(tonePin, 349, dur);
    delay(delayTime);
    tone(tonePin, 349, dur);
    delay(delayTime);
    tone(tonePin, 311, dur);
    delay(delayTime);
    tone(tonePin, 311, dur);
    delay(delayTime);
    tone(tonePin, 293, dur);
    delay(delayTime);
    tone(tonePin, 293, dur);
    delay(delayTime);
    tone(tonePin, 349, dur);
    delay(delayTime);
    tone(tonePin, 349, dur);
    delay(delayTime);
    tone(tonePin, 311, dur);
    delay(delayTime);
    tone(tonePin, 311, dur);
    delay(delayTime);
    tone(tonePin, 349, dur);
    delay(delayTime);
    tone(tonePin, 349, dur);
    delay(delayTime);
    tone(tonePin, 369, dur);
    delay(delayTime);
    tone(tonePin, 369, dur);
    delay(delayTime);
    tone(tonePin, 415, dur);
    delay(delayTime);
    tone(tonePin, 415, dur);
    delay(delayTime);
    tone(tonePin, 466, dur);
    delay(delayTime);
    delay(longDelayTime);
    tone(tonePin, 466, dur);
    delay(delayTime);
    tone(tonePin, 622, dur);
    delay(delayTime);
    tone(tonePin, 622, dur);
    delay(delayTime);
    tone(tonePin, 554, dur);
    delay(delayTime);
    tone(tonePin, 554, dur);
    delay(delayTime);
    tone(tonePin, 466, dur);
    delay(delayTime);
    delay(longDelayTime);
    tone(tonePin, 466, dur);
    delay(delayTime);
    tone(tonePin, 311, dur);
    delay(delayTime);
    delay(longDelayTime);
    tone(tonePin, 311, dur);
    delay(delayTime);
    tone(tonePin, 466, dur);
    delay(delayTime);
    tone(tonePin, 466, dur);
    delay(delayTime);
    tone(tonePin, 415, dur);
    delay(delayTime);
    tone(tonePin, 415, dur);
    delay(delayTime);
    tone(tonePin, 369, dur);
    delay(delayTime);
    tone(tonePin, 369, dur);
    delay(delayTime);
    tone(tonePin, 349, dur);
    delay(delayTime);
    tone(tonePin, 349, dur);
    delay(delayTime);
    tone(tonePin, 311, dur);
    delay(delayTime);
    tone(tonePin, 311, dur);
    delay(delayTime);
    tone(tonePin, 349, dur);
    delay(delayTime);
    tone(tonePin, 349, dur);
    delay(delayTime);
    tone(tonePin, 369, dur);
    delay(delayTime);
    tone(tonePin, 369, dur);
    delay(delayTime);
    tone(tonePin, 415, dur);
    delay(delayTime);
    tone(tonePin, 415, dur);
    delay(delayTime);
    tone(tonePin, 466, dur);
    delay(delayTime);
    delay(longDelayTime);
    tone(tonePin, 466, dur);
    delay(delayTime);
    tone(tonePin, 415, dur);
    delay(delayTime);
    tone(tonePin, 415, dur);
    delay(delayTime);
    tone(tonePin, 369, dur);
    delay(delayTime);
    tone(tonePin, 369, dur);
    delay(delayTime);
    tone(tonePin, 349, dur);
    delay(delayTime);
    delay(longDelayTime);
    tone(tonePin, 349, dur);
    delay(delayTime);
    tone(tonePin, 369, dur);
    delay(delayTime);
    delay(longDelayTime);
    tone(tonePin, 369, dur);
    delay(delayTime);
    tone(tonePin, 415, dur);
    delay(delayTime);
    delay(longDelayTime);
    tone(tonePin, 415, dur);
    delay(delayTime);
    tone(tonePin, 466, dur);
    delay(delayTime);
    delay(longDelayTime);
    tone(tonePin, 466, dur);
    delay(delayTime);
    tone(tonePin, 311, dur);
    delay(delayTime);
    tone(tonePin, 311, dur);
    delay(delayTime);
    tone(tonePin, 349, dur);
    delay(delayTime);
    tone(tonePin, 349, dur);
    delay(delayTime);
    tone(tonePin, 369, dur);
    delay(delayTime);
    tone(tonePin, 369, dur);
    delay(delayTime);
    tone(tonePin, 415, dur);
    delay(delayTime);
    tone(tonePin, 415, dur);
    delay(delayTime);
    tone(tonePin, 466, dur);
    delay(delayTime);
    delay(longDelayTime);
    tone(tonePin, 466, dur);
    delay(delayTime);
    tone(tonePin, 622, dur);
    delay(delayTime);
    tone(tonePin, 622, dur);
    delay(delayTime);
    tone(tonePin, 554, dur);
    delay(delayTime);
    tone(tonePin, 554, dur);
    delay(delayTime);
    tone(tonePin, 466, dur);
    delay(delayTime);
    delay(longDelayTime);
    tone(tonePin, 466, dur);
    delay(delayTime);
    tone(tonePin, 311, dur);
    delay(delayTime);
    delay(longDelayTime);
    tone(tonePin, 311, dur);
    delay(delayTime);
    tone(tonePin, 466, dur);
    delay(delayTime);
    tone(tonePin, 466, dur);
    delay(delayTime);
    tone(tonePin, 415, dur);
    delay(delayTime);
    tone(tonePin, 415, dur);
    delay(delayTime);
    tone(tonePin, 369, dur);
    delay(delayTime);
    tone(tonePin, 369, dur);
    delay(delayTime);
    tone(tonePin, 349, dur);
    delay(delayTime);
    tone(tonePin, 349, dur);
    delay(delayTime);
    tone(tonePin, 311, dur);
    delay(delayTime);
    tone(tonePin, 311, dur);
    delay(delayTime);
    tone(tonePin, 349, dur);
    delay(delayTime);
    tone(tonePin, 349, dur);
    delay(delayTime);
    tone(tonePin, 369, dur);
    delay(delayTime);
    tone(tonePin, 369, dur);
    delay(delayTime);
    tone(tonePin, 415, dur);
    delay(delayTime);
    tone(tonePin, 415, dur);
    delay(delayTime);
    tone(tonePin, 466, dur);
    delay(delayTime);
    delay(longDelayTime);
    tone(tonePin, 466, dur);
    delay(delayTime);
    tone(tonePin, 415, dur);
    delay(delayTime);
    tone(tonePin, 415, dur);
    delay(delayTime);
    tone(tonePin, 369, dur);
    delay(delayTime);
    tone(tonePin, 369, dur);
    delay(delayTime);
    tone(tonePin, 349, dur);
    delay(delayTime);
    tone(tonePin, 349, dur);
    delay(delayTime);
    tone(tonePin, 311, dur);
    delay(delayTime);
    tone(tonePin, 311, dur);
    delay(delayTime);
    tone(tonePin, 349, dur);
    delay(delayTime);
    tone(tonePin, 349, dur);
    delay(delayTime);
    tone(tonePin, 369, dur);
    delay(delayTime);
    tone(tonePin, 369, dur);
    delay(delayTime);
    tone(tonePin, 349, dur);
    delay(delayTime);
    tone(tonePin, 349, dur);
    delay(delayTime);
    tone(tonePin, 311, dur);
    delay(delayTime);
    tone(tonePin, 311, dur);
    delay(delayTime);
    tone(tonePin, 293, dur);
    delay(delayTime);
    tone(tonePin, 293, dur);
    delay(delayTime);
    tone(tonePin, 349, dur);
    delay(delayTime);
    tone(tonePin, 349, dur);
    delay(delayTime);
    tone(tonePin, 311, dur);
    delay(delayTime);
    tone(tonePin, 311, dur);
    delay(delayTime);
    tone(tonePin, 349, dur);
    delay(delayTime);
    tone(tonePin, 349, dur);
    delay(delayTime);
    tone(tonePin, 369, dur);
    delay(delayTime);
    tone(tonePin, 369, dur);
    delay(delayTime);
    tone(tonePin, 415, dur);
    delay(delayTime);
    tone(tonePin, 415, dur);
    delay(delayTime);
    tone(tonePin, 466, dur);
    delay(delayTime);
    delay(longDelayTime);
    tone(tonePin, 466, dur);
    delay(delayTime);
    tone(tonePin, 622, dur);
    delay(delayTime);
    tone(tonePin, 622, dur);
    delay(delayTime);
    tone(tonePin, 554, dur);
    delay(delayTime);
    tone(tonePin, 554, dur);
    delay(delayTime);
    tone(tonePin, 466, dur);
    delay(delayTime);
    delay(longDelayTime);
    tone(tonePin, 466, dur);
    delay(delayTime);
    tone(tonePin, 311, dur);
    delay(delayTime);
    delay(longDelayTime);
    tone(tonePin, 311, dur);
    delay(delayTime);
    tone(tonePin, 466, dur);
    delay(delayTime);
    tone(tonePin, 466, dur);
    delay(delayTime);
    tone(tonePin, 415, dur);
    delay(delayTime);
    tone(tonePin, 415, dur);
    delay(delayTime);
    tone(tonePin, 369, dur);
    delay(delayTime);
    tone(tonePin, 369, dur);
    delay(delayTime);
    tone(tonePin, 349, dur);
    delay(delayTime);
    tone(tonePin, 349, dur);
    delay(delayTime);
    tone(tonePin, 311, dur);
    delay(delayTime);
    tone(tonePin, 311, dur);
    delay(delayTime);
    tone(tonePin, 349, dur);
    delay(delayTime);
    tone(tonePin, 349, dur);
    delay(delayTime);
    tone(tonePin, 369, dur);
    delay(delayTime);
    tone(tonePin, 369, dur);
    delay(delayTime);
    tone(tonePin, 415, dur);
    delay(delayTime);
    tone(tonePin, 415, dur);
    delay(delayTime);
    tone(tonePin, 466, dur);
    delay(delayTime);
    delay(longDelayTime);
    tone(tonePin, 466, dur);
    delay(delayTime);
    tone(tonePin, 415, dur);
    delay(delayTime);
    tone(tonePin, 415, dur);
    delay(delayTime);
    tone(tonePin, 369, dur);
    delay(delayTime);
    tone(tonePin, 369, dur);
    delay(delayTime);
    tone(tonePin, 349, dur);
    delay(delayTime);
    delay(longDelayTime);
    tone(tonePin, 349, dur);
    delay(delayTime);
    tone(tonePin, 369, dur);
    delay(delayTime);
    delay(longDelayTime);
    tone(tonePin, 369, dur);
    delay(delayTime);
    tone(tonePin, 415, dur);
    delay(delayTime);
    delay(longDelayTime);
    tone(tonePin, 415, dur);
    delay(delayTime);
    tone(tonePin, 466, dur);
    delay(delayTime);
    delay(longDelayTime);
    tone(tonePin, 466, dur);
    delay(delayTime);
    tone(tonePin, 554, dur);
    delay(delayTime);
    tone(tonePin, 554, dur);
    delay(delayTime);
    tone(tonePin, 622, dur);
    delay(delayTime);
    tone(tonePin, 622, dur);
    delay(delayTime);
    tone(tonePin, 466, dur);
    delay(delayTime);
    tone(tonePin, 466, dur);
    delay(delayTime);
    tone(tonePin, 415, dur);
    delay(delayTime);
    tone(tonePin, 415, dur);
    delay(delayTime);
    tone(tonePin, 466, dur);
    delay(delayTime);
    delay(longDelayTime);
    tone(tonePin, 466, dur);
    delay(delayTime);
    tone(tonePin, 415, dur);
    delay(delayTime);
    tone(tonePin, 415, dur);
    delay(delayTime);
    tone(tonePin, 466, dur);
    delay(delayTime);
    tone(tonePin, 466, dur);
    delay(delayTime);
    tone(tonePin, 554, dur);
    delay(delayTime);
    tone(tonePin, 554, dur);
    delay(delayTime);
    tone(tonePin, 622, dur);
    delay(delayTime);
    tone(tonePin, 622, dur);
    delay(delayTime);
    tone(tonePin, 466, dur);
    delay(delayTime);
    tone(tonePin, 466, dur);
    delay(delayTime);
    tone(tonePin, 415, dur);
    delay(delayTime);
    tone(tonePin, 415, dur);
    delay(delayTime);
    tone(tonePin, 466, dur);
    delay(delayTime);
    delay(longDelayTime);
    tone(tonePin, 466, dur);
    delay(delayTime);
    tone(tonePin, 415, dur);
    delay(delayTime);
    tone(tonePin, 415, dur);
    delay(delayTime);
    tone(tonePin, 466, dur);
    delay(delayTime);
    tone(tonePin, 466, dur);
    delay(delayTime);
    tone(tonePin, 415, dur);
    delay(delayTime);
    tone(tonePin, 415, dur);
    delay(delayTime);
    tone(tonePin, 369, dur);
    delay(delayTime);
    tone(tonePin, 369, dur);
    delay(delayTime);
    tone(tonePin, 349, dur);
    delay(delayTime);
    tone(tonePin, 349, dur);
    delay(delayTime);
    tone(tonePin, 277, dur);
    delay(delayTime);
    tone(tonePin, 277, dur);
    delay(delayTime);
    tone(tonePin, 311, dur);
    delay(delayTime);
    delay(longDelayTime);
    tone(tonePin, 311, dur);
    delay(delayTime);
    tone(tonePin, 277, dur);
    delay(delayTime);
    tone(tonePin, 277, dur);
    delay(delayTime);
    tone(tonePin, 311, dur);
    delay(delayTime);
    tone(tonePin, 311, dur);
    delay(delayTime);
    tone(tonePin, 349, dur);
    delay(delayTime);
    tone(tonePin, 349, dur);
    delay(delayTime);
    tone(tonePin, 369, dur);
    delay(delayTime);
    tone(tonePin, 369, dur);
    delay(delayTime);
    tone(tonePin, 415, dur);
    delay(delayTime);
    tone(tonePin, 415, dur);
    delay(delayTime);
    tone(tonePin, 466, dur);
    delay(delayTime);
    tone(tonePin, 466, dur);
    delay(delayTime);
    tone(tonePin, 311, dur);
    delay(delayTime);
    delay(longDelayTime);
    tone(tonePin, 311, dur);
    delay(1000);
}

